
export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: 'Alchemy' | 'Tutor' | 'Graph' | 'Drive' | 'Social' | 'General';
  unlockedAt?: string;
  progress: number; // 0-100 or specific count
  goal: number;
  rewardXP: number;
  isSecret?: boolean; // Hidden until unlocked
  isAiGenerated?: boolean; // New: Created by Deep Learning analysis
}

export interface AIAchievementSuggestion {
  id: string;
  title: string;
  reason: string; // Why AI suggested this based on user behavior
  task: string;   // What the user specifically needs to do
  potentialReward: string;
  difficulty?: 'Easy' | 'Medium' | 'Hard'; // Added difficulty
}

// ... existing types ...

// --- BEHAVIOR TYPES ---
export type InteractionType = 
    | 'view_feature' 
    | 'complete_task' 
    | 'create_content' 
    | 'spend_time' 
    | 'click_element'
    | 'struggle'
    | 'excel';

export interface BehaviorLog {
    timestamp: number;
    type: InteractionType;
    context: string; // e.g., 'Alchemy', 'Tutor'
    detail?: string; // e.g., 'Created Flashcard', 'Score: 20%'
}

// ... rest of the file ...
export interface Testimonial {
  id: number;
  name: string;
  date: string;
  avatar: string;
  content: string;
  rating: number;
}
export interface Feature {
  icon: string;
  title: string;
  description: string;
}

export interface ChatMessage {
  id?: string;
  role: 'user' | 'model' | 'system';
  text: string;
  timestamp: Date | string;
}

export interface SavedChatSession {
  id: string;
  title: string;
  date: string;
  messages: ChatMessage[];
  personaId: string;
}

export interface TutorPersona {
  id: string;
  name: string;
  description: string;
  icon: string;
  systemInstruction: string;
  color: string;
}

export type LearningMethod = 'Flashcard' | 'Quiz' | 'Fill-in-the-blanks' | 'Spot the Error' | 'Case Study' | 'Mixed' | 'Code' | 'Document' | 'Video';

// SM-2 Data Structure for individual items
export interface SM2Data {
  repetitions: number;
  interval: number;
  efactor: number;
  nextReviewDate: string; // ISO string for easier serialization
}

// Content structures
export interface FlashcardItem {
  front: string;
  back: string;
  sm2: SM2Data;
}

export interface QuizItem {
  question: string;
  options: string[];
  correctAnswer: number; // Index of the correct option
  explanation: string;
  sm2: SM2Data;
}

export interface FillBlankItem {
  sentence: string; // The sentence with a blank (represented by underscores)
  answer: string;   // The word that fills the blank
  sm2: SM2Data;
}

export interface SpotErrorItem {
  text: string;       // The sentence containing an error
  error: string;      // Explanation of the error
  correction: string; // The corrected sentence
  sm2: SM2Data;
}

export interface CaseStudyItem {
  scenario: string;
  question: string;
  analysis: string;
  sm2: SM2Data;
}

export interface KnowledgeNode {
  id: string;
  title: string;
  type: LearningMethod;
  status: 'new' | 'learning' | 'mastered' | 'due' | 'future' | 'weak';
  tags?: string[]; // Smart clustering tags
  x: number; // Coordinate for graph (percentage or relative)
  y: number; // Coordinate for graph (percentage or relative)
  sourceUrl?: string;
  imageUrl?: string; // AI Generated Cover Image
  originalAuthor?: string; // The username of the creator if imported
  timestamp: Date | string;
  
  // Manual connections created by user (Graph View feature)
  connectedNodeIds?: string[];

  // Store the generated AI content here
  data?: {
    flashcards?: FlashcardItem[];
    quiz?: QuizItem[];
    fillInBlanks?: FillBlankItem[];
    spotErrors?: SpotErrorItem[];
    caseStudies?: CaseStudyItem[];
    summary?: string;
  };
}

// --- GAMIFICATION TYPES ---
export interface Quest {
    id: string;
    title: string;
    type: 'Daily' | 'Weekly' | 'Epic' | 'LearningPath';
    progress: number;
    total: number;
    reward: string;
    completed: boolean;
    description?: string;
    // For Learning Path Quests
    targetNodeIds?: string[]; 
}

// --- LEARNING PATH TYPES ---
export type PathLevelStatus = 'locked' | 'unlocked' | 'learning_passed' | 'completed';

export interface PathLevel {
    id: string;
    title: string;
    description: string;
    status: PathLevelStatus;
    stars?: number;
    // Data generated by AI for this specific level
    learningContent?: FlashcardItem[]; // 15 items
    quizContent?: QuizItem[]; // 10 items
}

export interface SavedLearningPath {
    id: string;
    title: string;
    createdAt: string;
    levels: PathLevel[];
    progress: number; // 0-100
}

// --- RANKED SYSTEM TYPES ---
export type RankTier = 'Iron' | 'Bronze' | 'Silver' | 'Gold' | 'Platinum' | 'Diamond' | 'Master' | 'Challenger' | 'Grandmaster';
export type RankDivision = 'IV' | 'III' | 'II' | 'I';

export interface MatchHistoryEntry {
    id: string;
    result: 'Victory' | 'Defeat'; // Based on session accuracy
    lpChange: number;
    timestamp: string;
}

export interface RankProfile {
    tier: RankTier;
    division: RankDivision;
    lp: number; // League Points (0-100)
    totalWins: number;
    totalLosses: number;
    seasonPoints: {
        daily: number;
        weekly: number;
        monthly: number;
    };
    matchHistory: MatchHistoryEntry[];
}

export interface LeaderboardEntry {
    id: string;
    name: string;
    avatar: string;
    tier: RankTier;
    lp: number; // For Master/Challenger sorting
    rank: number;
    rawScore?: number;
}

// --- DRAWING TYPES ---
export type ToolType = 'selection' | 'rectangle' | 'ellipse' | 'diamond' | 'arrow' | 'line' | 'freedraw' | 'text' | 'eraser' | 'highlighter' | 'hand' | 'sticker';
export type PageTemplate = 'blank' | 'grid' | 'ruled' | 'dotted';
export type CanvasMode = 'infinite' | 'page';

export interface DrawingPoint {
    x: number;
    y: number;
}

export interface DrawingElement {
    id: string;
    type: ToolType;
    x: number;
    y: number;
    width: number;
    height: number;
    strokeColor: string;
    backgroundColor: string;
    strokeWidth: number;
    opacity: number;
    fontSize?: number;
    points?: DrawingPoint[];
    text?: string;
    isDeleted?: boolean;
    stickerIcon?: string; // For sticker tool
}

export interface SavedDrawing {
    id: string;
    name: string;
    date: string;
    elements: DrawingElement[];
    template: PageTemplate;
    mode: CanvasMode;
    pageCount?: number;
}

// --- NOTELAB BLOCK TYPES ---
export type BlockType = 'text' | 'h1' | 'h2' | 'h3' | 'todo' | 'bullet' | 'code' | 'image' | 'quote';

export interface NoteBlock {
    id: string;
    type: BlockType;
    content: string; // HTML or Markdown content
    properties?: {
        checked?: boolean;
        language?: string;
        imageUrl?: string;
        caption?: string;
    };
}

export type FileSystemType = 'note' | 'folder' | 'project';

export interface NotePage {
    id: string;
    parentId: string | null; // For hierarchy
    type: FileSystemType;
    title: string;
    icon: string; // Emoji
    coverImage: string | null;
    blocks: NoteBlock[];
    updatedAt: Date | string;
    isFavorite?: boolean;
    isExpanded?: boolean; // For sidebar UI
    
    // Project specific
    projectMetadata?: {
        status: 'planning' | 'in-progress' | 'done' | 'paused';
        progress: number;
        dueDate?: Date | string;
    };
}

// --- TODO TYPES ---
export interface Subtask {
    id: string;
    content: string;
    isCompleted: boolean;
}

export interface TodoAttachment {
    id: string;
    name: string;
    url: string; // Could be object URL or base64
    type: 'image' | 'file';
}

export interface TodoComment {
    id: string;
    text: string;
    createdAt: string;
    author: string;
}

export type RecurrenceType = 'none' | 'daily' | 'weekly' | 'monthly';

export interface TodoTask {
    id: string;
    content: string;
    description?: string;
    priority: 1 | 2 | 3 | 4; // 4 is lowest (grey), 1 is highest (red)
    startDate?: string; // ISO string for Gantt
    dueDate: 'today' | 'tomorrow' | 'upcoming' | string | null; // Expanded to string for specific dates
    isCompleted: boolean;
    completedAt?: string; // ISO Date for stats
    projectId: string;
    tags?: string[];
    subtasks?: Subtask[];
    notes?: string;
    isMilestone?: boolean; // For Gantt/Project view
    
    // Advanced fields
    status?: 'backlog' | 'todo' | 'in-progress' | 'done'; // For Kanban
    attachments?: TodoAttachment[];
    comments?: TodoComment[];
    recurrence?: RecurrenceType;
    reminderTime?: string; // ISO string for specific reminder time
    isDeleted?: boolean; // Soft delete
    progress?: number;
    
    // Feature Link
    linkedFeature?: string; // 'alchemy' | 'tutor' | 'graph' etc.
}

export interface Project {
    id: string;
    name: string;
    color: string;
    icon: string;
}

// --- ALCHEMY ADVANCED TYPES ---
export type AlchemySourceType = 'text' | 'url' | 'youtube' | 'image' | 'audio' | 'batch';

export interface AlchemySource {
    id: string;
    type: AlchemySourceType;
    content: string; // The raw content or URL
    metadata?: {
        fileName?: string;
        duration?: string;
        language?: string;
        confidence?: number;
    };
}

export interface AlchemySettings {
    personaId: string;
    difficulty: number; // 0-100
    targetLanguage: string;
    templateId: string;
}

export interface AlchemyPersona {
    id: string;
    name: string;
    role: string;
    icon: string;
}

export interface AlchemyTemplate {
    id: string;
    name: string;
    description: string;
    icon: string;
}

// --- NEW: MARKETPLACE TYPES ---
export type MarketplaceItemType = 'Deck' | 'Link' | 'Video';

export interface MarketplaceItem {
    id: string;
    title: string;
    authorId: string; // ID of the user who created it
    author: string; // Display name
    type: MarketplaceItemType;
    price: string; // 'Free' or price
    rating: number;
    category: string;
    students: number; // or views/clicks
    url?: string; // For Link/Video types
    description?: string;
    payload?: any; // The actual data (KnowledgeNode, etc.) for importing
    timestamp: string;
}

// --- NEW: USER DATA TYPE ---
export interface UserAccount {
    id: string;
    email: string;
    password?: string; // In real app, this should be hashed. Here stored as plain/base64 for simulation.
    name: string;
    friendCode: string; // Unique short code for adding friends
    avatar: string;
    joinedDate: string;
    friends: string[]; // List of friend user IDs
    // Each user has their own data sandbox in localStorage logic
}

// --- NEW: USER FLOW INTENTS ---
export type AlchemyIntentType = 
    | 'create' // Standard
    | 'expand' // Context: Node -> Generate sub-nodes
    | 'refine' // Context: Node -> Improve content
    | 'connect' // Context: 2+ Nodes -> Find relation
    | 'visualize' // Context: Node -> Generate Image
    | 'quiz' // Context: Node -> Generate Quiz
    | 'repair' // Context: Broken Data -> Fix
    | 'search_create' // Context: Query -> Create
    | 'style_transfer'; // Context: Node -> Rewrite style

export interface AlchemyIntent {
    type: AlchemyIntentType;
    sourceNodes?: KnowledgeNode[]; // The nodes initiating the flow
    initialQuery?: string; // Search query or prompt override
}

// --- DRIVE TYPES ---
export type DriveFileType = 'pdf' | 'doc' | 'txt' | 'folder' | 'image' | 'unknown';

export interface DriveFile {
    id: string;
    parentId: string | null;
    name: string;
    type: DriveFileType;
    size?: string;
    lastModified: string;
    owner: string;
    isStarred: boolean;
    isTrashed: boolean;
    content?: string; // Mock content for embedding
    sharedWith?: string[];
}
